(WIP) i18n support and tooling
MarCnu/pdfXBlock pull request #6
Opened 2018-09-04 01:08 UTC by OmarIthawi

2018-09-11 19:25 UTC, OmarIthawi commented
@melvinsoft Could you please take a look here?

2018-09-11 23:16 UTC, MarCnu commented
I'll look at it tomorrow!

Le mar. 11 sept. 2018 21:25, Omar Al-Ithawi <notifications@github.com> a
écrit :

> @melvinsoft <https://github.com/melvinsoft> Could you please take a look
> here?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MarCnu/pdfXBlock/pull/6#issuecomment-420393052>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AHc8SsOE5fXfWsgNpiPMV5MbTuYZCiHHks5uaA49gaJpZM4WYJ0F>
> .
>

2018-09-12 08:11 UTC, OmarIthawi commented
Thanks a lot @MarCnu :slightly_smiling_face: 

Perhaps you've noticed that now this repo has it's own Transifex repo:
 - https://www.transifex.com/open-edx/xblocks/ (you need to be logged in to see the actual resources)

2018-10-09 22:34 UTC, melvinsoft reviewed
@OmarIthawi I started testing the Xblock in our Ficus devstack, and I've found a couple of issues with the requirements, after perform the installation following the README, the following requirements were updated and I needed to re install them manually.

`fs==2.1.1` 
and in Ficus we need
`fs==0.4.0`

`lxml==3.4.4`
and in Ficus we need
`lxml==3.4.4`

`python-dateutil==2.7.3`
and in Ficus we need
`python-dateutil==2.1`

Please let me know your thoughts

2018-10-10 14:20 UTC, OmarIthawi commented
Thanks @melvinsoft for you review. I've updated the requirements file to match what's in the [Google Drive XBlock](https://github.com/edx-solutions/xblock-google-drive/pull/27/files#diff-d9383e4fc78d9b72886e207884f8f14a).

However the `requirements-dev.txt` shouldn't make it into the Ficus devstack, in production at least that's the case.

2018-10-15 18:46 UTC, melvinsoft requested changes
@OmarIthawi I've found a couple of problems in the last changes on the `setup.py` please check my latests inline comments.

2018-10-15 18:46 UTC, melvinsoft commented on setup.py
> +    package_data=package_data("pdf", "static", "translations"),
@OmarIthawi There is a format error here, it should be `package_data=package_data("pdf", ["static", "translations"]),` and also change in the package data loop, to process the roots, like in the oppia XBlock:

```
def package_data(pkg, roots):
     """Generic function to find package_data.
 
     All of the files under each of the `roots` will be declared as package
     data for package `pkg`.
 
     """
     data = []
     for root in roots:
         for dirname, _, files in os.walk(os.path.join(pkg, root)):
             for fname in files:
                 data.append(os.path.relpath(os.path.join(dirname, fname), pkg))
 
     return {pkg: data}
```

2018-10-16 06:05 UTC, OmarIthawi commented
Thanks @melvinsoft! I've updated the PR. Please take another look.

2018-10-16 22:26 UTC, melvinsoft commented
@OmarIthawi Thanks for addressing the change, the install work good now. But I'm still experiencing error mentioned above. When I install the XBlock on my (Ficus) devstack, is upgrading three dependencies, that start conflicting with the edX one, and I cannot load the LMS anymore:

fs==2.1.1
and in Ficus we need
fs==0.4.0

lxml==3.4.4
and in Ficus we need
lxml==3.4.4

python-dateutil==2.7.3
and in Ficus we need
python-dateutil==2.1

☝️ Those are the upgraded dependencies, this isn't happening when I install the dev requirements, is happening when I install the XBlock. I'm gonna paste the commands to be sure:

```
sudo su edxapp -s /bin/bash
source /edx/app/edxapp/edxapp_env
cd /edx/src
pip install pdfXBlock/ --upgrade
```

2018-10-17 04:24 UTC, OmarIthawi commented
Thanks @melvinsoft. Please don't install using `pip install pdfXBlock/ --upgrade`. It should be fine if you refrain from using `--upgrade`.

2018-10-17 21:34 UTC, melvinsoft commented
@OmarIthawi 🤦‍♂️ Thanks! I think that was the problem. Sorry my mistake.

2018-10-17 21:34 UTC, melvinsoft approved these changes

2018-10-17 21:35 UTC, melvinsoft commented
@OmarIthawi Amazing work here! I'm approving the PR!

2018-10-17 21:43 UTC, OmarIthawi commented
Thanks @melvinsoft for the review here!

2018-10-17 21:49 UTC, OmarIthawi commented
@MarCnu would you like to get this merged in this repo? I would love to get it merged here so we don't end up in an synchronized forks.

As you can see the translation would end up being here as well, so I'll probably open one or two more pull requests to update the translations.

Depending on how would you like to move forward I see two options:

 - Get it merged here.
 - I take a hike and fork it :sweat_smile: 

Please let me know what do you think!

2018-11-29 12:49 UTC, OmarIthawi commented
Thank you @melvinsoft and @MarCnu. I'm closing this PR in favor of https://github.com/appsembler/pdfXBlock/pull/1.

2018-11-29 12:49 UTC, closed without merging